language: c
sudo: true

env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.1
 - GHCVER=7.10.2
 - GHCVER=7.10.3
 - GHCVER=8.0.2
 - GHCVER=head

script:
 - wget https://raw.github.com/ndmitchell/neil/master/travis.sh -O - --no-check-certificate --quiet | sh
